### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by tomoosting** [weissmanlab/magic#5]
Hi,

I'm running magic.py on my data and I keep getting the following error message:

Traceback (most recent call last):
  File "/nfs/home/oostinto/bin/magic/magic.py", line 633, in <module>
    full_params = infer_distribution(SLTpts, zeroPt=args.zero, family=args.family, npieces=args.components, niter=args.iterations, maxfun=args.maxfun, smoothing=args.smoothing)
  File "/nfs/home/oostinto/bin/magic/magic.py", line 398, in infer_distribution
    ans = scipy.optimize.basinhopping(func, guess, niter=niter, T=T, take_step=step, minimizer_kwargs={"method":"L-BFGS-B", 
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 617, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/nfs/home/oostinto/bin/magic/magic.py", line 311, in piece_exp_obj
    return np.sum( ((prefactors[i] @ postfactors[i] + p0 - obs[1]) / obs[2])**2 for i, obs in enumerate(mLTobs) ) + smoothing * np.linalg.norm(np.diff(np.log(rates)))**2
  File "<__array_function__ internals>", line 5, in sum
  File "/home/software/apps/local/lib/py38_new/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2230, in sum
    warnings.warn(
  File "/home/software/apps/python/3.8.1/lib/python3.8/warnings.py", line 109, in _showwarnmsg
    sw(msg.message, msg.category, msg.filename, msg.lineno,
  File "/nfs/home/oostinto/bin/magic/magic.py", line 597, in warn2file
    with open(file, 'a') as warnfile:
TypeError: expected str, bytes or os.PathLike object, not NoneType

I'm running the following commands, as advised in the README.md:

`combo_prep.py $in_ext.vcf.gz --coverfile LG1_cover.txt --masks $in_ext.mask.bed.gz > GL1.txt`
`windower.py LG1`
`magic.py LG1_counts.txt --out $LG1`

Any suggestions on how to fix this problem?
Many thanks!

**Comment by weissman** [comment]
Hi, in the commands you posted, it looks like there's a typo in the output
of the first line, which is going to GL1.txt instead of LG1.txt. Can you
fix that and post the content of LG1_counts.txt if that doesn't solve the
problem?

Thanks,
Daniel

**Comment by tomoosting** [comment]
Hi Daniel,

Thank you for the quick reply.
Sorry for the typo, I had the change the some wildcards I used in my scripts.

It doesn't appear to be problem.
I've tried running it under python3.7 and 3.8 but still get the same message.
I feel it's got something to do with one of the packages but can't figure it out.
It does create the _LT file but not the _final.txt

**Comment by weissman** [comment]
Got it. Can you share the _counts and _LT files (by, for example, putting
them in a public Dropbox and sending the link)? It could be that magic is
having trouble inferring enough points in the _LT file.

**Comment by tomoosting** [comment]
https://drive.google.com/drive/folders/1fNuK15VbbkEcqmtFdFHhKzgnPffYsAmB?usp=sharing

I attached the the results from two linkage groups and also tried merging them as indicated in the README.md.
The files are based on 5 indivuals.

**Comment by weissman** [comment]
It looks like something has changed in the warnings module. I tweaked the
code and it seems to work now. Can you try downloading the version of
magic.py and trying again?

Thanks,
Daniel

**Comment by tomoosting** [comment]
Hi Daniel,

Awesome, it works!
Thank you for looking into so quickly, much appriciated.

Cheers,
Tom
